### ISSUE TITLE
описка

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/seqelize_base#2]
https://github.com/Jaykob2447/seqelize_base/blob/2555d0d77a361ae8a17528a87b0047c164987c07/middleware/errorHeandlers.js#L7
- властивіть ерорки має бути `message`:
```javascript
 const massage = err.message || "Server Error"; 
``` 
Через це зараз на всі помилки надсилається _Server Error_

**Comment by Jaykob2447** [comment]
Я потім на терпівся з цією помилкоюколи переписував чат на WS тому певно запамьятаю

**Comment by pecourses** [comment]
Це найкращий спосіб запам'ятати  🙂
